belajar/belajar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
]

belajar/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("movies/", views.movielist, name="movies"),
    path("movie/new/", views.new_movie, name="new_movie"),
    path("movie/<int:pk>/", views.movie_detail, name="movie_detail"),
    path("movie/<int:pk>/edit/", views.edit_movie, name="edit_movie"),
    path("movie/<int:pk>/delete/", views.delete_movie, name="delete_movie"),
]

belajar/myapp/models.py
from django.db import models
from django.utils.translation import gettext as _


class GenreChoices(models.TextChoices):
    ACTION = "ACT", _("Action")
    DRAMA = "DRM", _("Drama")
    COMEDY = "COM", _("Comedy")


class MovieList(models.Model):
    title = models.CharField(max_length=200)
    genre = models.CharField(max_length=3, choices=GenreChoices.choices)
    year = models.IntegerField()

belajar/myapp/forms.py
from django import forms
from .models import MovieList, GenreChoices

class MovieForm(forms.ModelForm):
    class Meta:
        model = MovieList
        fields = ['title', 'genre', 'year']
        widgets = {
            'genre': forms.Select(choices=GenreChoices.choices)
        }

belajar/myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .models import MovieList
from .forms import MovieForm

# Create your views here.


def home(request):
    # return HttpResponse("Hello, Django!")
    return render(request, "home.html", {})


def movielist(request):
    items = MovieList.objects.all()
    return render(request, "movielist.html", {"movies": items})


def movie_detail(request, pk):
    item = get_object_or_404(MovieList, pk=pk)
    return render(request, "movie_detail.html", {"movie": item})


def new_movie(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect("movie_detail", pk=movie.pk)
    else:
        form = MovieForm()
    return render(
        request,
        "movie_form.html",
        {"form": form, "title": "New Movie", "cancel_url": reverse("movies")},
    )


def edit_movie(request, pk):
    movie = get_object_or_404(MovieList, pk=pk)
    if request.method == "POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect("movie_detail", pk=movie.pk)
    else:
        form = MovieForm(instance=movie)
    return render(
        request,
        "movie_edit.html",
        {
            "form": form,
            "title": "Edit Movie",
            "movie": movie,  # tambahkan ini ke konteks
            "cancel_url": reverse("movie_detail", args=[pk]),
        },
    )


def delete_movie(request, pk):
    movie = get_object_or_404(MovieList, pk=pk)
    if request.method == "POST":
        movie.delete()
        return redirect("movies")
    return render(request, "movie_confirm_delete.html", {"movie": movie})

belajar/myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Document{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

belajar/myapp/templates/home.html
{% extends "base.html" %} {% block title %} HomePage {% endblock %} 
{% block content %}
<h1>Welcome to my blog</h1>
<p>This is my first blog post</p>
<a href="/movies">Movies</a>
{% endblock %}

belajar/myapp/templates/movie_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete movie</h1>
<p>Are you sure you want to delete "{{ movie.title }}"?</p>
<form method="POST">
{% csrf_token %}
<button type="submit" class="btn btn-primary">Yes, delete</button>
</form>
<br/>
<a href="{% url 'movie_detail' pk=movie.pk %}"><button type="button" class="btn btn-primary">No, take me back</button></a>
{% endblock %}

belajar/myapp/templates/movie_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ movie.title }}</h1>
<p>Genre: {{ movie.get_genre_display }}</p>
<p>Year: {{ movie.year }}</p>
<a href="{% url 'edit_movie' pk=movie.pk %}">Edit</a> |
<a href="{% url 'delete_movie' pk=movie.pk %}">Delete</a> |
<a href="{% url 'movies' %}"><button type="button" class="btn btn-primary">Back to Movies</button></a>
{% endblock %}

belajar/myapp/templates/movie_edit.html
{% extends "base.html" %}
{% block content %}
<h1>New movie</h1>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-primary">Yes, save</button>
</form>
<br/>
<a href="{% url 'movie_detail' pk=movie.pk %}"><button type="button" class="btn btn-primary">No, take me back</button></a>
{% endblock %}

belajar/myapp/templates/movie_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="POST">
    {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Yes, save</button>
        <a href="{{ cancel_url }}"><button type="button" class="btn btn-primary">Cancel</button></a>
    </form>
{% endblock %}

belajar/myapp/templates/movielist.html
{% extends "base.html" %} {% block title %} Movie List {% endblock %} 
{% block content %}
<h1>Movie List</h1>
<a href="{% url 'new_movie' %}"><button type="button" class="btn btn-primary">new movie</button></a>
{% if movies %}
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Year</th>
                </tr>
            </thead>
            <tbody>
                {% for movie in movies %}
                    <tr>
                        <td><a href="{% url 'movie_detail' pk=movie.pk %}">{{ movie.title }}</a></td>
                        <td>{{ movie.get_genre_display }}</td>
                        <td>{{ movie.year }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No movies available.</p>
    {% endif %}
    <a href="{% url 'home' %}"><button type="button" class="btn btn-primary">Back to Home</button></a>
{% endblock %}